"""init

Revision ID: 03ac087824b7
Revises: 
Create Date: 2023-11-03 06:07:12.285610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy.orm
import sqlalchemy.ext.asyncio


# revision identifiers, used by Alembic.
revision: str = '03ac087824b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
