"""update fields with default

Revision ID: 5777a823d0fd
Revises: 03ac087824b7
Create Date: 2023-11-03 06:14:58.902011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy.orm
import sqlalchemy.ext.asyncio


# revision identifiers, used by Alembic.
revision: str = '5777a823d0fd'
down_revision: Union[str, None] = '03ac087824b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column(
        'title', sa.String(), nullable=True))
    op.drop_column('podcasts', 'lastEpisode')
    op.add_column('users', sa.Column(
        'lastPodcastId', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column(
        'lastEpisodeId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastEpisodeId')
    op.drop_column('users', 'lastPodcastId')
    op.add_column('podcasts', sa.Column(
        'lastEpisode', sa.INTEGER(), nullable=True))
    op.drop_column('episodes', 'title')
    # ### end Alembic commands ###
